services:
  evepraisal:
    container_name: evepraisal
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/evepraisal/db
      - ./evepraisal.toml:/evepraisal/evepraisal.toml
    restart: always
    ports:
      - 8080:8080
      - 8090:8090
