version: '3.3'
services:
  evepraisal:
    container_name: evepraisal
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./evepraisal.toml:/evepraisal/evepraisal.toml
    restart: always
    networks:
      - proxy-bridge
networks:
    proxy-bridge:
       external: true